const canvas=document.getElementById("renderCanvas"),engine=new BABYLON.Engine(canvas,true,{preserveDrawingBuffer:true,stencil:true});let scene,player,marker,moves=0,energy=5,xp=1,cq=0,character="boy",tiles=[],reachable=[],gridSize=8,goalReached=false,started=false,returnOptions={zip:false,glide:false,boat:false},peakPos=null;let shadowGen,cam,riverMat,playerParts={};
function mat(name,color,emissive){let m=new BABYLON.StandardMaterial(name,scene);m.diffuseColor=BABYLON.Color3.FromHexString(color);m.specularColor=new BABYLON.Color3(.08,.08,.08);if(emissive)m.emissiveColor=BABYLON.Color3.FromHexString(emissive);return m}
function createScene(){scene=new BABYLON.Scene(engine);scene.clearColor=new BABYLON.Color4(.025,.07,.045,1);scene.fogMode=BABYLON.Scene.FOGMODE_EXP2;scene.fogDensity=.012;scene.fogColor=new BABYLON.Color3(.04,.09,.06);
cam=new BABYLON.ArcRotateCamera("camera",-Math.PI/2,1.02,24,new BABYLON.Vector3(0,0,0),scene);cam.attachControl(canvas,true);cam.lowerRadiusLimit=13;cam.upperRadiusLimit=31;cam.lowerBetaLimit=.55;cam.upperBetaLimit=1.28;cam.wheelPrecision=35;
let hemi=new BABYLON.HemisphericLight("sky",new BABYLON.Vector3(0,1,0),scene);hemi.intensity=.65;hemi.diffuse=new BABYLON.Color3(.65,.82,.68);let sun=new BABYLON.DirectionalLight("sun",new BABYLON.Vector3(-.6,-1,.4),scene);sun.position=new BABYLON.Vector3(10,18,-12);sun.intensity=1.2;shadowGen=new BABYLON.ShadowGenerator(1024,sun);shadowGen.useBlurExponentialShadowMap=true;shadowGen.blurKernel=24;
let ground=BABYLON.MeshBuilder.CreateGround("ground",{width:24,height:24,subdivisions:2},scene);ground.material=mat("earth","#29482d");ground.position.y=-.18;let border=BABYLON.MeshBuilder.CreateGround("border",{width:19,height:19},scene);border.position.y=.03;border.material=mat("grass","#52743a");
for(let z=0;z<gridSize;z++)for(let x=0;x<gridSize;x++){let t=BABYLON.MeshBuilder.CreateGround("tile",{width:2.12,height:2.12},scene);t.position.set((x-(gridSize-1)/2)*2.2,.06,(z-(gridSize-1)/2)*2.2);t.metadata={x,z};t.material=mat("t"+x+z,(x+z)%3===0?"#77964b":(x+z)%3===1?"#6c8945":"#809d50");tiles.push(t);t.receiveShadows=true;t.actionManager=new BABYLON.ActionManager(scene);t.actionManager.registerAction(new BABYLON.ExecuteCodeAction(BABYLON.ActionManager.OnPickTrigger,()=>moveTo(t)));
if(Math.random()<.34 && !(x===0&&z===0)&&!(x===gridSize-1&&z===gridSize-1))tree(t.position.x+(Math.random()-.5)*.8,t.position.z+(Math.random()-.5)*.8)}
terrainDetails();let edge=(gridSize-1)*1.1;river();camp(-edge,-edge);marker=createMarker(edge,edge);player=createPlayer(-edge,-edge);fire(-7.1,-7.35);fireflies();landmark(-5.4,-2.3,2);landmark(4.5,-4.8,5);landmark(5.5,4.7,8);backpack(-3.1,4.6);backpack(4,-.9);highlightMoves();scene.onBeforeRenderObservable.add(animateWorld);return scene}
function tree(x,z){let trunk=BABYLON.MeshBuilder.CreateCylinder("trunk",{height:.75,diameter:.25},scene);trunk.position.set(x,.4,z);trunk.material=mat("bark","#49301e");shadowGen.addShadowCaster(trunk);for(let i=0;i<2;i++){let crown=BABYLON.MeshBuilder.CreateCylinder("pine",{height:1.3,diameterTop:0,diameterBottom:1.25-i*.25,tessellation:8},scene);crown.position.set(x,1+i*.55,z);crown.material=mat("leaf",i?"#1f5b35":"#2d7040");shadowGen.addShadowCaster(crown)}}
function river(){riverMat=mat("water","#1688ad","#063846");riverMat.alpha=.9;riverMat.specularColor=new BABYLON.Color3(.55,.75,.8);for(let z=-8.2;z<=8.2;z+=.7){let x=Math.sin(z*.42)*1.35;let w=BABYLON.MeshBuilder.CreateGround("water",{width:2.5,height:.9,subdivisions:1},scene);w.position.set(x,.13,z);w.rotation.y=-Math.sin(z*.42)*.22;w.material=riverMat}bridge(.2,-.2);bridge(-.95,5.0)}
function peak(){let edge=(gridSize-1)*1.1;peakPos=new BABYLON.Vector3(edge*.62,0,-edge*.52);for(let i=0;i<4;i++){let m=BABYLON.MeshBuilder.CreateCylinder("peak",{height:1.2+i*.45,diameterTop:.2,diameterBottom:2.8-i*.35,tessellation:7},scene);m.position.set(peakPos.x+i*.18,.5+i*.45,peakPos.z+i*.15);m.material=mat("mountain","#596055");shadowGen.addShadowCaster(m)}returnOptions.glide=true;returnOptions.zip=true}
function bridge(x,z){for(let i=-3;i<=3;i++){let p=BABYLON.MeshBuilder.CreateBox("plank",{width:.38,height:.13,depth:2.55},scene);p.position.set(x+i*.36,.3,z);p.material=mat("bridgewood","#815126");shadowGen.addShadowCaster(p)}}
function rock(x,z,s=.7){let r=BABYLON.MeshBuilder.CreatePolyhedron("rock",{type:1,size:s},scene);r.scaling.y=.7;r.position.set(x,s*.45,z);r.rotation.y=Math.random()*3;r.material=mat("rockmat","#716f62");shadowGen.addShadowCaster(r);return r}
function landmark(x,z,level){let r=rock(x,z,.85);let disc=BABYLON.MeshBuilder.CreateCylinder("challenge",{height:.08,diameter:.85,tessellation:24},scene);disc.position.set(x,.75,z);disc.material=mat("challengeMat",level>6?"#9f302b":"#d1a348",level>6?"#3d0805":"#49320b");let dt=new BABYLON.DynamicTexture("num"+level,{width:128,height:128},scene);dt.drawText(String(level),42,88,"bold 72px Georgia","white","transparent",true);let dm=new BABYLON.StandardMaterial("nummat"+level,scene);dm.diffuseTexture=dt;dm.opacityTexture=dt;let num=BABYLON.MeshBuilder.CreatePlane("num",{size:.7},scene);num.billboardMode=BABYLON.Mesh.BILLBOARDMODE_ALL;num.position.set(x,.82,z);num.material=dm;return r}
function backpack(x,z){let b=BABYLON.MeshBuilder.CreateBox("resource",{width:.65,height:.8,depth:.35},scene);b.position.set(x,.55,z);b.material=mat("pack","#9a5d23");let flap=BABYLON.MeshBuilder.CreateCylinder("flap",{height:.38,diameter:.66,tessellation:12},scene);flap.rotation.x=Math.PI/2;flap.position.set(x,.88,z);flap.material=b.material;shadowGen.addShadowCaster(b);return b}
function camp(x,z){let tent=BABYLON.MeshBuilder.CreateCylinder("base",{height:1.4,diameterTop:0,diameterBottom:2,tessellation:4},scene);tent.position.set(x,.75,z);tent.rotation.y=Math.PI/4;tent.material=mat("tent","#d59b35","#38200b");shadowGen.addShadowCaster(tent)}
function createMarker(x,z){let pole=BABYLON.MeshBuilder.CreateCylinder("marco",{height:2.4,diameter:.15},scene);pole.position.set(x,1.2,z);pole.material=mat("pole","#6e4a2a");let flag=BABYLON.MeshBuilder.CreatePlane("flag",{width:1.2,height:.7},scene);flag.position.set(x+.62,1.9,z);flag.material=mat("flagmat","#d43d2f","#49100c");return pole}
function createPlayer(x,z){let root=new BABYLON.TransformNode("player",scene),skin=mat("skin","#d99b6c"),uniform=mat("uniform","#476e3b"),brown=mat("leather","#54301d"),red=mat("scarf","#b92f27");
let torso=BABYLON.MeshBuilder.CreateCylinder("torso",{height:1.05,diameterTop:.62,diameterBottom:.78,tessellation:10},scene);torso.parent=root;torso.position.y=1.05;torso.material=uniform;
let head=BABYLON.MeshBuilder.CreateSphere("head",{diameter:.62,segments:16},scene);head.parent=root;head.position.y=1.82;head.material=skin;
let hair=BABYLON.MeshBuilder.CreateSphere("hair",{diameter:.65,segments:12,slice:.52},scene);hair.parent=root;hair.position.y=1.95;hair.material=brown;
let brim=BABYLON.MeshBuilder.CreateCylinder("brim",{height:.07,diameter:1.0,tessellation:18},scene);brim.parent=root;brim.position.y=2.13;brim.material=brown;
let crown=BABYLON.MeshBuilder.CreateCylinder("crown",{height:.28,diameterTop:.52,diameterBottom:.66,tessellation:12},scene);crown.parent=root;crown.position.y=2.27;crown.material=brown;
let scarf=BABYLON.MeshBuilder.CreateTorus("scarf",{diameter:.58,thickness:.1,tessellation:16},scene);scarf.parent=root;scarf.position.y=1.5;scarf.rotation.x=Math.PI/2;scarf.material=red;
let pack=BABYLON.MeshBuilder.CreateBox("backpack",{width:.65,height:.82,depth:.34},scene);pack.parent=root;pack.position.set(0,1.05,.42);pack.material=mat("packmat","#765126");
let armL=BABYLON.MeshBuilder.CreateCapsule("armL",{height:.9,radius:.12},scene),armR=armL.clone("armR"),legL=BABYLON.MeshBuilder.CreateCapsule("legL",{height:1,radius:.14},scene),legR=legL.clone("legR");
[armL,armR,legL,legR].forEach(p=>{p.parent=root;p.material=uniform;shadowGen.addShadowCaster(p)});armL.position.set(-.48,1.08,0);armR.position.set(.48,1.08,0);legL.position.set(-.2,.42,0);legR.position.set(.2,.42,0);legL.material=legR.material=mat("shorts","#6b4d2e");
playerParts={root,torso,head,hair,brim,crown,scarf,pack,armL,armR,legL,legR};root.position.set(x,.12,z);[torso,head,hair,brim,crown,scarf,pack].forEach(p=>shadowGen.addShadowCaster(p));applyCharacter();return root}
function applyCharacter(){if(!playerParts.root)return;let girl=character==="girl";playerParts.hair.scaling.set(girl?1.12:1,girl?1.18:1,girl?1.12:1);playerParts.hair.position.y=girl?1.88:1.95;playerParts.torso.scaling.x=girl?.9:1;playerParts.pack.scaling.setAll(girl?.92:1)}
function animateScoutWalk(on){let p=playerParts;if(!p.armL)return;let a=on?.65:0;p.armL.rotation.x=a;p.armR.rotation.x=-a;p.legL.rotation.x=-a*.65;p.legR.rotation.x=a*.65;if(on)setTimeout(()=>{p.armL.rotation.x=-a;p.armR.rotation.x=a;p.legL.rotation.x=a*.65;p.legR.rotation.x=-a*.65},220);else [p.armL,p.armR,p.legL,p.legR].forEach(x=>x.rotation.x=0)}
function highlightMoves(){tiles.forEach(t=>{t.renderOutline=false});reachable=[];if(!player||moves<=0)return;tiles.forEach(t=>{let d=Math.hypot(t.position.x-player.position.x,t.position.z-player.position.z);if(d>1&&d<3.2){reachable.push(t);t.renderOutline=true;t.outlineColor=new BABYLON.Color3(.45,1,.48);t.outlineWidth=.08}})}
function fire(x,z){let light=new BABYLON.PointLight("fire",new BABYLON.Vector3(x,.8,z),scene);light.diffuse=new BABYLON.Color3(1,.45,.12);light.intensity=2;light.range=5;let ps=new BABYLON.ParticleSystem("embers",350,scene);ps.particleTexture=new BABYLON.Texture("https://assets.babylonjs.com/textures/flare.png",scene);ps.emitter=new BABYLON.Vector3(x,.25,z);ps.minEmitBox=new BABYLON.Vector3(-.12,0,-.12);ps.maxEmitBox=new BABYLON.Vector3(.12,.1,.12);ps.color1=new BABYLON.Color4(1,.35,.04,1);ps.color2=new BABYLON.Color4(1,.85,.18,1);ps.minSize=.03;ps.maxSize=.11;ps.minLifeTime=.25;ps.maxLifeTime=.8;ps.emitRate=70;ps.direction1=new BABYLON.Vector3(-.15,1,-.15);ps.direction2=new BABYLON.Vector3(.15,1.5,.15);ps.gravity=new BABYLON.Vector3(0,.4,0);ps.start()}
function fireflies(){let ps=new BABYLON.ParticleSystem("fireflies",180,scene);ps.particleTexture=new BABYLON.Texture("https://assets.babylonjs.com/textures/flare.png",scene);ps.emitter=new BABYLON.Vector3(0,1,0);ps.minEmitBox=new BABYLON.Vector3(-9,0,-9);ps.maxEmitBox=new BABYLON.Vector3(9,2,9);ps.color1=new BABYLON.Color4(.7,1,.25,.7);ps.color2=new BABYLON.Color4(1,.85,.2,.5);ps.minSize=.025;ps.maxSize=.07;ps.minLifeTime=2;ps.maxLifeTime=5;ps.emitRate=18;ps.direction1=new BABYLON.Vector3(-.1,.05,-.1);ps.direction2=new BABYLON.Vector3(.1,.25,.1);ps.start()}
function terrainDetails(){for(let i=0;i<34;i++){let x=(Math.random()-.5)*20,z=(Math.random()-.5)*20;if(Math.abs(x)<1.8)continue;let r=rock(x,z,.18+Math.random()*.24);r.position.y=.05}for(let i=0;i<45;i++){let x=(Math.random()-.5)*19,z=(Math.random()-.5)*19;if(Math.abs(x)<1.6)continue;let g=BABYLON.MeshBuilder.CreateCylinder("grass",{height:.18+Math.random()*.25,diameterTop:0,diameterBottom:.18,tessellation:4},scene);g.position.set(x,.12,z);g.material=mat("grassBlade","#416b35")}}
function animateWorld(){let time=performance.now()*.001;if(riverMat)riverMat.emissiveColor=new BABYLON.Color3(.02+.018*Math.sin(time*1.7),.16+.025*Math.sin(time*1.3),.22+.035*Math.sin(time));}
function cameraFocus(target,done){let from=cam.target.clone(),to=target.clone();to.y=.4;BABYLON.Animation.CreateAndStartAnimation("camFocus",cam,"target",30,22,from,to,BABYLON.Animation.ANIMATIONLOOPMODE_CONSTANT,null,done)}
function moveTo(t){if(!started)return;if(moves<=0)return toast("Role o D12 primeiro.");let dx=t.position.x-player.position.x,dz=t.position.z-player.position.z;if(Math.hypot(dx,dz)>3.2)return toast("Escolha uma casa vizinha.");moves--;document.getElementById("moves").textContent=moves;let start=player.position.clone(),end=new BABYLON.Vector3(t.position.x,.12,t.position.z);let anim=new BABYLON.Animation("walk","position",30,BABYLON.Animation.ANIMATIONTYPE_VECTOR3,BABYLON.Animation.ANIMATIONLOOPMODE_CONSTANT);anim.setKeys([{frame:0,value:start},{frame:7,value:new BABYLON.Vector3((start.x+end.x)/2,.55,(start.z+end.z)/2)},{frame:14,value:end}]);player.animations=[anim];animateScoutWalk(true);scene.beginAnimation(player,0,14,false,1.15,()=>{animateScoutWalk(false);highlightMoves();if(Math.random()<.16)cameraFocus(player.position,()=>setTimeout(()=>cameraFocus(BABYLON.Vector3.Zero()),650))});if(Math.random()<.13){cq=Math.min(10,cq+1);update();toast("🎒 Recurso encontrado! +1 Conquista")}let edge=(gridSize-1)*1.1;if(!goalReached&&Math.hypot(player.position.x-edge,player.position.z-edge)<2.4){goalReached=true;cq=Math.min(10,cq+2);update();setTimeout(()=>{configureReturns();document.getElementById("returnPanel").classList.remove("hidden")},700)}}
function update(){energyEl.textContent=energy+"/10";xpEl.textContent=xp+"/8";cqEl.textContent=cq+"/10";em.value=energy;xm.value=xp;cm.value=cq}
function toast(s){let e=document.getElementById("toast");e.textContent=s;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1600)}
engine.runRenderLoop(()=>scene&&scene.render());window.addEventListener("resize",()=>engine.resize());
const energyEl=document.getElementById("energy"),xpEl=document.getElementById("xp"),cqEl=document.getElementById("cq"),em=document.getElementById("em"),xm=document.getElementById("xm"),cm=document.getElementById("cm");
document.getElementById("roll").onclick=()=>{if(!started||goalReached)return;let d=document.getElementById("die");d.classList.add("rolling");setTimeout(()=>{moves=1+Math.floor(Math.random()*12);d.textContent=moves;document.getElementById("moves").textContent=moves;d.classList.remove("rolling");toast("🎲 "+moves+" movimentos disponíveis");highlightMoves();},400)};
let selectedChar="boy",selectedSize=8;document.querySelectorAll("[data-pick]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-pick]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");selectedChar=b.dataset.pick});document.querySelectorAll("[data-size]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-size]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");selectedSize=+b.dataset.size});document.getElementById("startGame").onclick=()=>{character=selectedChar;gridSize=selectedSize;started=true;document.getElementById("startScreen").classList.add("hidden");document.getElementById("charTitle").textContent=character==="boy"?"ESCOTEIRO":"ESCOTEIRA";document.getElementById("charBadge").textContent=character==="boy"?"🧑🏻‍🦱":"👧🏻";document.getElementById("difficultyLabel").textContent=gridSize===6?"Trilha Curta · 6 × 6":gridSize===8?"Aventura · 8 × 8":"Expedição · 10 × 10";createScene();toast("⚜ Sempre Alerta! Sua jornada começou.")};function configureReturns(){let map={zip:"returnZip",glide:"returnGlide",boat:"returnBoat"};returnOptions.boat=true;Object.entries(map).forEach(([k,id])=>{let b=document.getElementById(id);if(!b)return;b.disabled=!returnOptions[k];b.classList.toggle("locked",!returnOptions[k])})}
function specialReturn(type){if(!returnOptions[type])return toast("Este retorno não está disponível neste mapa.");document.getElementById("returnPanel").classList.add("hidden");moves=0;let edge=(gridSize-1)*1.1,end=new BABYLON.Vector3(-edge,.12,-edge),name=type==="zip"?"🪢 Tirolesa":type==="glide"?"🪂 Asa-delta":"🛶 Passeio de bote";toast(name+" para o acampamento!");let start=player.position.clone(),anim=new BABYLON.Animation("return","position",30,BABYLON.Animation.ANIMATIONTYPE_VECTOR3,BABYLON.Animation.ANIMATIONLOOPMODE_CONSTANT),height=type==="glide"?6:type==="zip"?4:.4;anim.setKeys([{frame:0,value:start},{frame:45,value:new BABYLON.Vector3((start.x+end.x)/2,height,(start.z+end.z)/2)},{frame:90,value:end}]);player.animations=[anim];scene.beginAnimation(player,0,90,false,1,()=>{cq=Math.min(10,cq+1);update();document.getElementById("finishText").textContent=(character==="boy"?"O Escoteiro":"A Escoteira")+" retornou ao acampamento com "+cq+" Conquista(s). Sempre Alerta!";document.getElementById("finishPanel").classList.remove("hidden")})}document.querySelectorAll("[data-return]").forEach(b=>b.onclick=()=>specialReturn(b.dataset.return));document.getElementById("playAgain").onclick=()=>location.reload();
document.getElementById("newGame").onclick=()=>location.reload();document.getElementById("rules").onclick=()=>alert("Role o D12 e mova-se por casas vizinhas. Explore a trilha, encontre recursos, alcance o Marco e retorne à Base.");
update();