const canvas=document.getElementById("renderCanvas"),engine=new BABYLON.Engine(canvas,true,{preserveDrawingBuffer:true,stencil:true});let scene,player,marker,moves=0,energy=5,xp=1,cq=0,character="boy",tiles=[],reachable=[];let shadowGen;
function mat(name,color,emissive){let m=new BABYLON.StandardMaterial(name,scene);m.diffuseColor=BABYLON.Color3.FromHexString(color);m.specularColor=new BABYLON.Color3(.08,.08,.08);if(emissive)m.emissiveColor=BABYLON.Color3.FromHexString(emissive);return m}
function createScene(){scene=new BABYLON.Scene(engine);scene.clearColor=new BABYLON.Color4(.025,.07,.045,1);scene.fogMode=BABYLON.Scene.FOGMODE_EXP2;scene.fogDensity=.012;scene.fogColor=new BABYLON.Color3(.04,.09,.06);
let cam=new BABYLON.ArcRotateCamera("camera",-Math.PI/2,1.02,24,new BABYLON.Vector3(0,0,0),scene);cam.attachControl(canvas,true);cam.lowerRadiusLimit=13;cam.upperRadiusLimit=31;cam.lowerBetaLimit=.55;cam.upperBetaLimit=1.28;cam.wheelPrecision=35;
let hemi=new BABYLON.HemisphericLight("sky",new BABYLON.Vector3(0,1,0),scene);hemi.intensity=.65;hemi.diffuse=new BABYLON.Color3(.65,.82,.68);let sun=new BABYLON.DirectionalLight("sun",new BABYLON.Vector3(-.6,-1,.4),scene);sun.position=new BABYLON.Vector3(10,18,-12);sun.intensity=1.2;shadowGen=new BABYLON.ShadowGenerator(1024,sun);shadowGen.useBlurExponentialShadowMap=true;shadowGen.blurKernel=24;
let ground=BABYLON.MeshBuilder.CreateGround("ground",{width:24,height:24,subdivisions:2},scene);ground.material=mat("earth","#29482d");let border=BABYLON.MeshBuilder.CreateGround("border",{width:19,height:19},scene);border.position.y=.03;border.material=mat("grass","#52743a");
for(let z=0;z<8;z++)for(let x=0;x<8;x++){let t=BABYLON.MeshBuilder.CreateGround("tile",{width:2.12,height:2.12},scene);t.position.set((x-3.5)*2.2,.06,(z-3.5)*2.2);t.metadata={x,z};t.material=mat("t"+x+z,(x+z)%3===0?"#77964b":(x+z)%3===1?"#6c8945":"#809d50");tiles.push(t);t.receiveShadows=true;t.actionManager=new BABYLON.ActionManager(scene);t.actionManager.registerAction(new BABYLON.ExecuteCodeAction(BABYLON.ActionManager.OnPickTrigger,()=>moveTo(t)));
if(Math.random()<.34 && !(x===0&&z===0)&&!(x===7&&z===7))tree(t.position.x+(Math.random()-.5)*.8,t.position.z+(Math.random()-.5)*.8)}
river();camp(-7.7,-7.7);marker=createMarker(7.7,7.7);player=createPlayer(-7.7,-7.7);fire(-7.1,-7.35);fireflies();highlightMoves();return scene}
function tree(x,z){let trunk=BABYLON.MeshBuilder.CreateCylinder("trunk",{height:.75,diameter:.25},scene);trunk.position.set(x,.4,z);trunk.material=mat("bark","#49301e");shadowGen.addShadowCaster(trunk);for(let i=0;i<2;i++){let crown=BABYLON.MeshBuilder.CreateCylinder("pine",{height:1.3,diameterTop:0,diameterBottom:1.25-i*.25,tessellation:8},scene);crown.position.set(x,1+i*.55,z);crown.material=mat("leaf",i?"#1f5b35":"#2d7040");shadowGen.addShadowCaster(crown)}}
function river(){for(let z=-7.7;z<=7.7;z+=1.1){let w=BABYLON.MeshBuilder.CreateGround("water",{width:2.2,height:1.3},scene);w.position.set(Math.sin(z*.45)*1.2,.12,z);let wm=mat("water","#187ca0","#063846");wm.alpha=.88;w.material=wm}}
function camp(x,z){let tent=BABYLON.MeshBuilder.CreateCylinder("base",{height:1.4,diameterTop:0,diameterBottom:2,tessellation:4},scene);tent.position.set(x,.75,z);tent.rotation.y=Math.PI/4;tent.material=mat("tent","#d59b35","#38200b");shadowGen.addShadowCaster(tent)}
function createMarker(x,z){let pole=BABYLON.MeshBuilder.CreateCylinder("marco",{height:2.4,diameter:.15},scene);pole.position.set(x,1.2,z);pole.material=mat("pole","#6e4a2a");let flag=BABYLON.MeshBuilder.CreatePlane("flag",{width:1.2,height:.7},scene);flag.position.set(x+.62,1.9,z);flag.material=mat("flagmat","#d43d2f","#49100c");return pole}
function createPlayer(x,z){let root=new BABYLON.TransformNode("player",scene),body=BABYLON.MeshBuilder.CreateCapsule("body",{height:1.45,radius:.35},scene);body.parent=root;body.position.y=.85;body.material=mat("uniform","#476e3b");let head=BABYLON.MeshBuilder.CreateSphere("head",{diameter:.65,segments:12},scene);head.parent=root;head.position.y=1.72;head.material=mat("skin","#d99b6c");let hat=BABYLON.MeshBuilder.CreateCylinder("hat",{height:.18,diameterTop:.75,diameterBottom:1.05,tessellation:12},scene);hat.parent=root;hat.position.y=2.07;hat.material=mat("hatmat","#5a321d");root.position.set(x,.12,z);shadowGen.addShadowCaster(body);shadowGen.addShadowCaster(head);shadowGen.addShadowCaster(hat);return root}
function highlightMoves(){tiles.forEach(t=>{t.renderOutline=false});reachable=[];if(!player||moves<=0)return;tiles.forEach(t=>{let d=Math.hypot(t.position.x-player.position.x,t.position.z-player.position.z);if(d>1&&d<3.2){reachable.push(t);t.renderOutline=true;t.outlineColor=new BABYLON.Color3(.45,1,.48);t.outlineWidth=.08}})}
function fire(x,z){let light=new BABYLON.PointLight("fire",new BABYLON.Vector3(x,.8,z),scene);light.diffuse=new BABYLON.Color3(1,.45,.12);light.intensity=2;light.range=5;let ps=new BABYLON.ParticleSystem("embers",350,scene);ps.particleTexture=new BABYLON.Texture("https://assets.babylonjs.com/textures/flare.png",scene);ps.emitter=new BABYLON.Vector3(x,.25,z);ps.minEmitBox=new BABYLON.Vector3(-.12,0,-.12);ps.maxEmitBox=new BABYLON.Vector3(.12,.1,.12);ps.color1=new BABYLON.Color4(1,.35,.04,1);ps.color2=new BABYLON.Color4(1,.85,.18,1);ps.minSize=.03;ps.maxSize=.11;ps.minLifeTime=.25;ps.maxLifeTime=.8;ps.emitRate=70;ps.direction1=new BABYLON.Vector3(-.15,1,-.15);ps.direction2=new BABYLON.Vector3(.15,1.5,.15);ps.gravity=new BABYLON.Vector3(0,.4,0);ps.start()}
function fireflies(){let ps=new BABYLON.ParticleSystem("fireflies",180,scene);ps.particleTexture=new BABYLON.Texture("https://assets.babylonjs.com/textures/flare.png",scene);ps.emitter=new BABYLON.Vector3(0,1,0);ps.minEmitBox=new BABYLON.Vector3(-9,0,-9);ps.maxEmitBox=new BABYLON.Vector3(9,2,9);ps.color1=new BABYLON.Color4(.7,1,.25,.7);ps.color2=new BABYLON.Color4(1,.85,.2,.5);ps.minSize=.025;ps.maxSize=.07;ps.minLifeTime=2;ps.maxLifeTime=5;ps.emitRate=18;ps.direction1=new BABYLON.Vector3(-.1,.05,-.1);ps.direction2=new BABYLON.Vector3(.1,.25,.1);ps.start()}
function moveTo(t){if(moves<=0)return toast("Role o D12 primeiro.");let dx=t.position.x-player.position.x,dz=t.position.z-player.position.z;if(Math.hypot(dx,dz)>3.2)return toast("Escolha uma casa vizinha.");moves--;document.getElementById("moves").textContent=moves;let start=player.position.clone(),end=new BABYLON.Vector3(t.position.x,.12,t.position.z);let anim=new BABYLON.Animation("walk","position",30,BABYLON.Animation.ANIMATIONTYPE_VECTOR3,BABYLON.Animation.ANIMATIONLOOPMODE_CONSTANT);anim.setKeys([{frame:0,value:start},{frame:7,value:new BABYLON.Vector3((start.x+end.x)/2,.55,(start.z+end.z)/2)},{frame:14,value:end}]);player.animations=[anim];scene.beginAnimation(player,0,14,false,1.15,()=>highlightMoves());if(Math.random()<.13){cq=Math.min(10,cq+1);update();toast("🎒 Recurso encontrado! +1 Conquista")}}
function update(){energyEl.textContent=energy+"/10";xpEl.textContent=xp+"/8";cqEl.textContent=cq+"/10";em.value=energy;xm.value=xp;cm.value=cq}
function toast(s){let e=document.getElementById("toast");e.textContent=s;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1600)}
createScene();engine.runRenderLoop(()=>scene.render());window.addEventListener("resize",()=>engine.resize());
const energyEl=document.getElementById("energy"),xpEl=document.getElementById("xp"),cqEl=document.getElementById("cq"),em=document.getElementById("em"),xm=document.getElementById("xm"),cm=document.getElementById("cm");
document.getElementById("roll").onclick=()=>{let d=document.getElementById("die");d.classList.add("rolling");setTimeout(()=>{moves=1+Math.floor(Math.random()*12);d.textContent=moves;document.getElementById("moves").textContent=moves;d.classList.remove("rolling");toast("🎲 "+moves+" movimentos disponíveis");highlightMoves();},400)};
document.querySelectorAll(".chars button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".chars button").forEach(x=>x.classList.remove("active"));b.classList.add("active");character=b.dataset.char;toast(character==="boy"?"Escoteiro selecionado":"Escoteira selecionada")});
document.getElementById("newGame").onclick=()=>location.reload();document.getElementById("rules").onclick=()=>alert("Role o D12 e mova-se por casas vizinhas. Explore a trilha, encontre recursos, alcance o Marco e retorne à Base.");
update();